//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.9.0.0 (NJsonSchema v9.7.3.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Server.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Server.Controllers
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.9.0.0")]
    public interface IAnController
    {
        /// <summary>Sendet eine Authentifizierungsanfrage an den Server [AllowAnonymous]</summary>
        /// <param name="credentials">Eine ASCII-Zeichenfolge mit mindestens einem Zeichen.</param>
        /// <returns>Returns nothing</returns>
        System.Threading.Tasks.Task<SwaggerResponse<AuthResponse>> AuthenticateAsync(CredentialDto credentials);
        /// <summary>Sendet eine RefreshToken Abfrage an den Server [AllowAnonymous]</summary>
        /// <param name="refreshtokenparameter">Eine ASCII-Zeichenfolge mit mindestens einem Zeichen.</param>
        /// <returns>AuthResponse</returns>
        System.Threading.Tasks.Task<SwaggerResponse<AuthResponse>> RefreshtokenAsync(RefreshTokenDto refreshtokenparameter);
        /// <summary>Einen Benutzer registrieren [AllowAnonymous]</summary>
        /// <param name="registerDto">Registrierungsinformationen</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit einem Bestätigungslink.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<RegisterResponse>> RegisterUserAsync(RegisterDto registerDto);
        /// <summary>Eine Benutzerregistrierung bestätigen [AllowAnonymous]</summary>
        /// <param name="id">Userid</param>
        /// <param name="cnf">Confirmationtoken</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<ConfirmResponse>> ConfirmRegisterAsync(string id, string cnf);
        /// <summary>Passwort wiederherstellen [AllowAnonymous]</summary>
        /// <param name="recoverPasswordParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit einem Passwortresetcode.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<RecoverPasswordResponse>> RecoverPasswordAsync(RecoverPasswordParams recoverPasswordParams);
        /// <summary>Abfrage des Usernamens [AllowAnonymous]</summary>
        /// <param name="recoverUsernameParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit seinem Benutzernamen.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<RecoverUsernameResponse>> RecoverUsernameAsync(RecoverUsernameParams recoverUsernameParams);
        /// <summary>Ein Benutzer setzt ein neues Passwort [AllowAnonymous]</summary>
        /// <param name="setPasswordParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<SetPasswordResponse>> SetPasswordAsync(SetPasswordParams setPasswordParams);
        /// <summary>Abfrage aller Profile</summary>
        /// <returns>Die Operation war erfolgreich.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<GetProfilesResponse>> GetProfilesAsync();
        /// <summary>Abfrage des eigenen Profils</summary>
        /// <returns>Die Operation war erfolgreich.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<GetProfileResponse>> GetMyProfileAsync();
        /// <summary>Abfrage eines Benutzerprofiles</summary>
        /// <param name="userid">User Id</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        System.Threading.Tasks.Task<SwaggerResponse<GetProfileResponse>> GetProfileAsync(string userid);
        /// <summary>Get the list of users [Authorize(Policy = "RequireApiAdminRole")]</summary>
        /// <returns>Returns nothing</returns>
        System.Threading.Tasks.Task<SwaggerResponse<UsersDto>> AdminGetUsersAsync();
        /// <summary>Get the list of sessions [Authorize(Policy = "RequireApiAdminRole")]</summary>
        /// <returns>Returns nothing</returns>
        System.Threading.Tasks.Task<SwaggerResponse<SessionsDto>> AdminGetSessionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "11.9.0.0")]
    [Route("api/v1")]
    public partial class AnController : Microsoft.AspNetCore.Mvc.Controller 
    {
        private IAnController _implementation; 
    
        public AnController(IAnController implementation)
        {
            _implementation = implementation; 
        }
    	private IActionResult HandleInvalidModelState(ModelStateDictionary model)
        {
            var errors = "";
            foreach (var state in ModelState)
            {
                foreach (var error in state.Value.Errors)
                {
                    errors += error.ErrorMessage + "; ";
                }
            }
            var authResponse = new { Status = new { Success = false, Result = errors.TrimEnd(new[] { ';', ' ' }) } };
            return new ObjectResult(authResponse) { StatusCode = 404 };
          }
        /// <summary>Sendet eine Authentifizierungsanfrage an den Server [AllowAnonymous]</summary>
        /// <param name="credentials">Eine ASCII-Zeichenfolge mit mindestens einem Zeichen.</param>
        /// <returns>Returns nothing</returns>
        [AllowAnonymous]
        [HttpPost, Route("authenticate")]
        public async System.Threading.Tasks.Task<IActionResult> Authenticate([FromBody]CredentialDto credentials)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.AuthenticateAsync(credentials);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Sendet eine RefreshToken Abfrage an den Server [AllowAnonymous]</summary>
        /// <param name="refreshtokenparameter">Eine ASCII-Zeichenfolge mit mindestens einem Zeichen.</param>
        /// <returns>AuthResponse</returns>
        [AllowAnonymous]
        [HttpPost, Route("refreshtoken")]
        public async System.Threading.Tasks.Task<IActionResult> Refreshtoken([FromBody]RefreshTokenDto refreshtokenparameter)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.RefreshtokenAsync(refreshtokenparameter);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Einen Benutzer registrieren [AllowAnonymous]</summary>
        /// <param name="registerDto">Registrierungsinformationen</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit einem Bestätigungslink.</returns>
        [AllowAnonymous]
        [HttpPost, Route("register")]
        public async System.Threading.Tasks.Task<IActionResult> RegisterUser([FromBody]RegisterDto registerDto)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.RegisterUserAsync(registerDto);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Eine Benutzerregistrierung bestätigen [AllowAnonymous]</summary>
        /// <param name="id">Userid</param>
        /// <param name="cnf">Confirmationtoken</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        [AllowAnonymous]
        [HttpGet, Route("confirm")]
        public async System.Threading.Tasks.Task<IActionResult> ConfirmRegister([FromQuery]string id, [FromQuery]string cnf)
        {
            var result = await _implementation.ConfirmRegisterAsync(id, cnf);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Passwort wiederherstellen [AllowAnonymous]</summary>
        /// <param name="recoverPasswordParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit einem Passwortresetcode.</returns>
        [AllowAnonymous]
        [HttpPost, Route("recoverPassword")]
        public async System.Threading.Tasks.Task<IActionResult> RecoverPassword([FromBody]RecoverPasswordParams recoverPasswordParams)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.RecoverPasswordAsync(recoverPasswordParams);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Abfrage des Usernamens [AllowAnonymous]</summary>
        /// <param name="recoverUsernameParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich. Der Benutzer erhält eine E-Mail mit seinem Benutzernamen.</returns>
        [AllowAnonymous]
        [HttpPost, Route("recoverUsername")]
        public async System.Threading.Tasks.Task<IActionResult> RecoverUsername([FromBody]RecoverUsernameParams recoverUsernameParams)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.RecoverUsernameAsync(recoverUsernameParams);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Ein Benutzer setzt ein neues Passwort [AllowAnonymous]</summary>
        /// <param name="setPasswordParams">Wiederherstellungsparameter</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        [AllowAnonymous]
        [HttpPost, Route("setPassword")]
        public async System.Threading.Tasks.Task<IActionResult> SetPassword([FromBody]SetPasswordParams setPasswordParams)
        {
            if(!ModelState.IsValid) return HandleInvalidModelState(ModelState);
            var result = await _implementation.SetPasswordAsync(setPasswordParams);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Abfrage aller Profile</summary>
        /// <returns>Die Operation war erfolgreich.</returns>
        [HttpGet, Route("profiles")]
        public async System.Threading.Tasks.Task<IActionResult> GetProfiles()
        {
            var result = await _implementation.GetProfilesAsync();
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Abfrage des eigenen Profils</summary>
        /// <returns>Die Operation war erfolgreich.</returns>
        [HttpGet, Route("profiles/myprofile")]
        public async System.Threading.Tasks.Task<IActionResult> GetMyProfile()
        {
            var result = await _implementation.GetMyProfileAsync();
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Abfrage eines Benutzerprofiles</summary>
        /// <param name="userid">User Id</param>
        /// <returns>Die Operation war erfolgreich.</returns>
        [HttpGet, Route("profiles/{userid}")]
        public async System.Threading.Tasks.Task<IActionResult> GetProfile([FromRoute]string userid)
        {
            var result = await _implementation.GetProfileAsync(userid);
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Get the list of users [Authorize(Policy = "RequireApiAdminRole")]</summary>
        /// <returns>Returns nothing</returns>
        [Authorize(Policy = "RequireApiAdminRole")]
        [HttpGet, Route("admin/users")]
        public async System.Threading.Tasks.Task<IActionResult> AdminGetUsers()
        {
            var result = await _implementation.AdminGetUsersAsync();
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
        /// <summary>Get the list of sessions [Authorize(Policy = "RequireApiAdminRole")]</summary>
        /// <returns>Returns nothing</returns>
        [Authorize(Policy = "RequireApiAdminRole")]
        [HttpGet, Route("admin/sessions")]
        public async System.Threading.Tasks.Task<IActionResult> AdminGetSessions()
        {
            var result = await _implementation.AdminGetSessionsAsync();
    			foreach (var header in result.Headers)
    				ControllerContext.HttpContext.Response.Headers.Add(header.Key, header.Value.ToArray());
    			if (result.StatusCode == 200)
    				return Ok(result.Result);
    			else
    				return new ObjectResult(result.Result) { StatusCode = result.StatusCode };
    		}
    }
    
    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class AuthResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
        private int? _validFor;
        private string _id;
        private string _token;
        private string _refreshtoken;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The token will be valid for validFor seconds</summary>
        [Newtonsoft.Json.JsonProperty("validFor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? ValidFor
        {
            get { return _validFor; }
            set 
            {
                if (_validFor != value)
                {
                    _validFor = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The user id</summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Id
        {
            get { return _id; }
            set 
            {
                if (_id != value)
                {
                    _id = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Ein Authentifizierungstoken mit dem alle folgenden Aufrufe authentifiziert werden.</summary>
        [Newtonsoft.Json.JsonProperty("token", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Token
        {
            get { return _token; }
            set 
            {
                if (_token != value)
                {
                    _token = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Ein RefreshToken mit dem der token erneuert werden kann.</summary>
        [Newtonsoft.Json.JsonProperty("refreshtoken", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Refreshtoken
        {
            get { return _refreshtoken; }
            set 
            {
                if (_refreshtoken != value)
                {
                    _refreshtoken = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static AuthResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<AuthResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class CredentialDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _client_type;
        private string _username;
        private string _password;
    
        /// <summary>Der Client-Typ 'web', 'ionic'</summary>
        [Newtonsoft.Json.JsonProperty("client_type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Client_type
        {
            get { return _client_type; }
            set 
            {
                if (_client_type != value)
                {
                    _client_type = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Die E-Mail Adresse 1 .. 160 Zeichen. Wird benötigt für die Bestätigung der Kontoerstellung.</summary>
        [Newtonsoft.Json.JsonProperty("username", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Username
        {
            get { return _username; }
            set 
            {
                if (_username != value)
                {
                    _username = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Das Passwort 1 .. 80 Zeichen. Wird für die Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("password", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Password
        {
            get { return _password; }
            set 
            {
                if (_password != value)
                {
                    _password = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static CredentialDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<CredentialDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RefreshTokenDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _refresh_token;
    
        /// <summary>Der Refresh Token</summary>
        [Newtonsoft.Json.JsonProperty("refresh_token", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Refresh_token
        {
            get { return _refresh_token; }
            set 
            {
                if (_refresh_token != value)
                {
                    _refresh_token = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RefreshTokenDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RefreshTokenDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RegisterDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _firstname;
        private string _name;
        private string _email;
        private string _username;
        private string _password;
    
        /// <summary>Der Vorname, 1 .. 80 Zeichen</summary>
        [Newtonsoft.Json.JsonProperty("firstname", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Firstname
        {
            get { return _firstname; }
            set 
            {
                if (_firstname != value)
                {
                    _firstname = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Der Name, 1 .. 80 Zeichen</summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name
        {
            get { return _name; }
            set 
            {
                if (_name != value)
                {
                    _name = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Die E-Mail Adresse 1 .. 160 Zeichen. Wird benötigt für die Bestätigung der Kontoerstellung.</summary>
        [Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Email
        {
            get { return _email; }
            set 
            {
                if (_email != value)
                {
                    _email = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Der Benutzername 1 .. 80 Zeichen. Wird für das Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("username", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Username
        {
            get { return _username; }
            set 
            {
                if (_username != value)
                {
                    _username = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Das Passwort 1 .. 80 Zeichen. Wird für die Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("password", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Password
        {
            get { return _password; }
            set 
            {
                if (_password != value)
                {
                    _password = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RegisterDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RegisterDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RegisterResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RegisterResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RegisterResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class ConfirmResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static ConfirmResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ConfirmResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RecoverPasswordParams : System.ComponentModel.INotifyPropertyChanged
    {
        private string _email;
        private string _username;
    
        /// <summary>Die E-Mail Adresse 1 .. 160 Zeichen. Wird benötigt für die Bestätigung der Kontoerstellung.</summary>
        [Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Email
        {
            get { return _email; }
            set 
            {
                if (_email != value)
                {
                    _email = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Der Benutzername 1 .. 80 Zeichen. Wird für das Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("username", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Username
        {
            get { return _username; }
            set 
            {
                if (_username != value)
                {
                    _username = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RecoverPasswordParams FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RecoverPasswordParams>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RecoverUsernameParams : System.ComponentModel.INotifyPropertyChanged
    {
        private string _email;
    
        /// <summary>Die E-Mail Adresse 1 .. 160 Zeichen. Wird benötigt für die Bestätigung der Kontoerstellung.</summary>
        [Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Email
        {
            get { return _email; }
            set 
            {
                if (_email != value)
                {
                    _email = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RecoverUsernameParams FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RecoverUsernameParams>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RecoverPasswordResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RecoverPasswordResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RecoverPasswordResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RecoverUsernameResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RecoverUsernameResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RecoverUsernameResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SetPasswordParams : System.ComponentModel.INotifyPropertyChanged
    {
        private string _code;
        private string _username;
        private string _password;
    
        /// <summary>Der Passwortresetcode.</summary>
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code
        {
            get { return _code; }
            set 
            {
                if (_code != value)
                {
                    _code = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Der Benutzername 1 .. 80 Zeichen. Wird für das Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("username", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Username
        {
            get { return _username; }
            set 
            {
                if (_username != value)
                {
                    _username = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Das Passwort 1 .. 80 Zeichen. Wird für die Anmeldung benötigt.</summary>
        [Newtonsoft.Json.JsonProperty("password", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Password
        {
            get { return _password; }
            set 
            {
                if (_password != value)
                {
                    _password = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static SetPasswordParams FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SetPasswordParams>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SetPasswordResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static SetPasswordResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SetPasswordResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class GetProfilesResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static GetProfilesResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<GetProfilesResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class GetProfileResponse : System.ComponentModel.INotifyPropertyChanged
    {
        private OpResult _status;
    
        [Newtonsoft.Json.JsonProperty("status", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public OpResult Status
        {
            get { return _status; }
            set 
            {
                if (_status != value)
                {
                    _status = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static GetProfileResponse FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<GetProfileResponse>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class UsersDto : System.ComponentModel.INotifyPropertyChanged
    {
        private System.Collections.Generic.List<UserDto> _users;
    
        [Newtonsoft.Json.JsonProperty("users", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<UserDto> Users
        {
            get { return _users; }
            set 
            {
                if (_users != value)
                {
                    _users = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static UsersDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<UsersDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class UserDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _id;
        private string _firstName;
        private string _lastName;
        private string _email;
        private bool? _emailConfirmed;
        private double? _accessFailedCount;
        private System.Collections.Generic.List<RoleDto> _roleNames;
    
        /// <summary>Then user id</summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Id
        {
            get { return _id; }
            set 
            {
                if (_id != value)
                {
                    _id = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The first name of user</summary>
        [Newtonsoft.Json.JsonProperty("firstName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string FirstName
        {
            get { return _firstName; }
            set 
            {
                if (_firstName != value)
                {
                    _firstName = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The last name of user</summary>
        [Newtonsoft.Json.JsonProperty("lastName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LastName
        {
            get { return _lastName; }
            set 
            {
                if (_lastName != value)
                {
                    _lastName = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The email of the user</summary>
        [Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Email
        {
            get { return _email; }
            set 
            {
                if (_email != value)
                {
                    _email = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The confirmed status of the user registration</summary>
        [Newtonsoft.Json.JsonProperty("emailConfirmed", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? EmailConfirmed
        {
            get { return _emailConfirmed; }
            set 
            {
                if (_emailConfirmed != value)
                {
                    _emailConfirmed = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The number of failed access attempts</summary>
        [Newtonsoft.Json.JsonProperty("accessFailedCount", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AccessFailedCount
        {
            get { return _accessFailedCount; }
            set 
            {
                if (_accessFailedCount != value)
                {
                    _accessFailedCount = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        [Newtonsoft.Json.JsonProperty("roleNames", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<RoleDto> RoleNames
        {
            get { return _roleNames; }
            set 
            {
                if (_roleNames != value)
                {
                    _roleNames = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static UserDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<UserDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class RoleDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _name;
    
        /// <summary>Name of role</summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Name
        {
            get { return _name; }
            set 
            {
                if (_name != value)
                {
                    _name = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static RoleDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<RoleDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SessionsDto : System.ComponentModel.INotifyPropertyChanged
    {
        private System.Collections.Generic.List<SessionDto> _sessions;
    
        [Newtonsoft.Json.JsonProperty("sessions", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<SessionDto> Sessions
        {
            get { return _sessions; }
            set 
            {
                if (_sessions != value)
                {
                    _sessions = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static SessionsDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SessionsDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class SessionDto : System.ComponentModel.INotifyPropertyChanged
    {
        private string _id;
        private string _userid;
        private string _email;
        private string _created;
        private bool? _isStop;
    
        /// <summary>Then sessions id</summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Id
        {
            get { return _id; }
            set 
            {
                if (_id != value)
                {
                    _id = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The userid associated with the session</summary>
        [Newtonsoft.Json.JsonProperty("userid", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Userid
        {
            get { return _userid; }
            set 
            {
                if (_userid != value)
                {
                    _userid = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>the email of the user</summary>
        [Newtonsoft.Json.JsonProperty("email", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Email
        {
            get { return _email; }
            set 
            {
                if (_email != value)
                {
                    _email = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>The timestamp of the creation</summary>
        [Newtonsoft.Json.JsonProperty("created", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Created
        {
            get { return _created; }
            set 
            {
                if (_created != value)
                {
                    _created = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>True if the session is stopped</summary>
        [Newtonsoft.Json.JsonProperty("isStop", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IsStop
        {
            get { return _isStop; }
            set 
            {
                if (_isStop != value)
                {
                    _isStop = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static SessionDto FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<SessionDto>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.7.3.0 (Newtonsoft.Json v9.0.0.0)")]
    public partial class OpResult : System.ComponentModel.INotifyPropertyChanged
    {
        private bool? _success;
        private string _result;
    
        /// <summary>True wenn die Operation erfolgreich war</summary>
        [Newtonsoft.Json.JsonProperty("success", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? Success
        {
            get { return _success; }
            set 
            {
                if (_success != value)
                {
                    _success = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        /// <summary>Eine Text-Meldung</summary>
        [Newtonsoft.Json.JsonProperty("result", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Result
        {
            get { return _result; }
            set 
            {
                if (_result != value)
                {
                    _result = value; 
                    RaisePropertyChanged();
                }
            }
        }
    
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static OpResult FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<OpResult>(data);
        }
    
        protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
        {
            var handler = PropertyChanged;
            if (handler != null) 
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }

}